Added URI protocol prefixes, 'mqtt://' and 'mqtts://'
eclipse/paho.mqtt.c pull request #1270
Opened 2022-09-21 21:09 UTC by fpagliughi

A number of other libraries and tools use the `mqtt://` and `mqtts://` schemes for MQTT URI's, which makes it difficult to mix in applications using Paho C/C++/Rust, since you need to know which tools were written with which libraries to create a URI.

The `mqtt://` and `mqtts://` schemes also appears on the MQTT.org wiki: 
https://github.com/mqtt/mqtt.org/wiki/URI-Scheme

This PR **adds** these two schemes without changing existing behavior:
```
    mqtt://   <==>  tcp://
    mqtts://  <==>  ssl://
```

This PR does _not_, however:
- Address the web sockets, which could probably do something similar to CoAP, like `mqtt+ws://`, etc
- Implement username and password in the URI, which would be a nice addition.

2022-09-24 11:04 UTC, icraggs requested changes
Thanks. Could we have some addition to the docs in MQTTClient.h and MQTTAsync.h and change a couple of tests to use the new prefixes?

2022-09-27 13:46 UTC, fpagliughi commented
Will do.

2022-09-28 10:03 UTC, icraggs approved these changes
Thanks very much Frank!

2022-09-28 12:57 UTC, icraggs commented
P.S. Would you like to open an issue for these?

- Address the web sockets, which could probably do something similar to CoAP, like mqtt+ws://, etc
- Implement username and password in the URI, which would be a nice addition.

2022-09-28 15:36 UTC, merged