Linking under Windows (MinGW 5.3.0)
eclipse/paho.mqtt.c pull request #576
Opened 2018-11-03 11:20 UTC by CapitanFuture

Need of link crypt32 and RpcRT4 for referencing 'CryptStringToBinary' and 'UUidCreate' in a mingw toolchain environment. 

src/CMakeFiles/common_obj.dir/Base64.c.obj:Base64.c:(.text+0x44): undefined reference to `_imp__CryptStringToBinaryA@28'
src/CMakeFiles/common_obj.dir/Base64.c.obj:Base64.c:(.text+0x94): undefined reference to `_imp__CryptBinaryToStringA@20'
src/CMakeFiles/common_obj.dir/WebSocket.c.obj:WebSocket.c:(.text+0xe1): undefined reference to `_imp__UuidCreate@4'

2018-11-25 19:50 UTC, tbeu requested changes
OK

2018-11-25 22:34 UTC, tbeu approved these changes

2019-05-30 15:05 UTC, CapitanFuture commented
What must I do to see this PR in master ? 
What means ip-validation problem ?

2019-05-30 15:43 UTC, icraggs commented
Hi.  Thanks for the PR and for asking.  The IP validation checks that:

1) you've signed an ECA (https://www.eclipse.org/legal/ECA.php) with the email address you used to make the PR, and 
2) you've used the git --signoff option when creating the commit, again with the same email address.

The CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md files contain this information.

2019-12-04 10:32 UTC, icraggs commented
Changes made to the develop branch.  Thanks.

2019-12-04 10:32 UTC, closed without merging