Fix calling convention for 'InitOnceFunction' for windows with STATIC…
eclipse/paho.mqtt.c pull request #855
Opened 2020-04-23 10:20 UTC by mkfix

Fix calling convention for 'InitOnceFunction' for windows with STATIC build

Signed-off-by: Madhu Kumar <madhu.kumar@nxp.com>

2020-04-23 11:38 UTC, icraggs requested changes
I think this should be CALLBACK rather than WINAPI.

For me to merge changes directly, you would also have to sign the contributor agreement.

2020-04-23 21:31 UTC, fpagliughi commented
D'Oh! Could this have been what was hanging the startup we were testing last week? I'll definitely try this one change with the Rust client that kept getting hung up.

2020-04-24 07:05 UTC, mkfix commented
Seems like one of the jobs stalled and failed. Can you please check and if it's ok merge the fix?

2020-04-24 08:35 UTC, icraggs commented
@fpagliughi unlikely - this is for MQTTClient.c not MQTTAsync.c.

2020-04-24 10:15 UTC, icraggs approved these changes

2020-04-24 10:15 UTC, merged